openapi: 3.1.0
info:
  title: TodoMVC
  version: '1.0'
  summary: This API is a backend storage solution for the TodoMVC project.
  description: The TodoMVC API allows you persist data from any implementation of the TodoMVC frontend project.
  contact:
    url: 'https://www.longhornphp.com'
servers:
  - url: 'http://localhost:3000'
paths:
  /todos:
    get:
      summary: Get Todos
      tags:
        - Todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  $ref: '#/components/schemas/Todo'
              examples: {}
      operationId: get-todos
      description: Get all todos
    post:
      summary: Create Todo
      tags:
        - Todos
      operationId: post-todos
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
      description: Create a new todo
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
        description: ''
  '/todos/{todoId}':
    parameters:
      - schema:
          type: integer
          minimum: 1
        name: todoId
        in: path
        required: true
        description: Todo ID
    patch:
      summary: Update Todo
      tags:
        - Todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
      operationId: patch-todos-todoId
      description: Update the details of a single todo.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
    delete:
      summary: Delete Todo
      tags:
        - Todos
      responses:
        '204':
          description: No Content
      operationId: delete-todos-todoId
components:
  schemas:
    Todo:
      title: Todo
      type: object
      x-tags:
        - Todos
      description: A task that needs to be done or has been done
      properties:
        id:
          type: integer
          minimum: 1
          readOnly: true
        title:
          type: string
        completed:
          type: boolean
      required:
        - id
        - title
      examples:
        - id: 1
          title: Complete Sponsor Bingo card
          completed: false
        - id: 2
          title: Purchase Longhorn PHP ticket
          completed: true
tags:
  - name: Todos
