openapi: 3.1.0
info:
  title: TodoMVC
  version: '1.0'
  summary: This API is a backend storage solution for the TodoMVC project.
  description: The TodoMVC API allows you persist data from any implementation of the TodoMVC frontend project.
  contact:
    url: 'https://www.longhornphp.com'
servers:
  - url: 'http://localhost:3000'
paths:
  /todos:
    get:
      summary: Get Todos
      tags:
        - Todos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    id:
                      type: integer
                      minimum: 1
                    title:
                      type: string
                    completed:
                      type: boolean
                  required:
                    - id
                    - title
                    - completed
              examples:
                example-1:
                  value:
                    - id: 1
                      title: Complete Sponsor Bingo Card
                      completed: false
                    - id: 2
                      title: Rate talks on Joind.in
                      completed: false
      operationId: get-todos
      description: Get all todos
components:
  schemas: {}
tags:
  - name: Todos
